#!/bin/bash

#This script is used to run the DC evaluation.

#****Variable Declaration****

XLext=".xls*" #This is the pattern used to find the excel extension in a string.
XLdir=${@%%${XLext}} #This is the directory name where the zip file will be extracted

#****Function Declaration****

#Creates the zip file corresponding to the excel file in question.
#The zip file is then extracted into a folder with the same name as the
#excel file, minus the ".xls*" extension.

createXLzip () {
    cp "${*}" "${XLdir}.zip"
    if ! [[ -d ${XLdir} ]]
    then
	mkdir "${XLdir}"
    else
	rm -rf "${XLdir}"
	mkdir "${XLdir}"
    fi
    unzip -q "${XLdir}.zip" -d "${XLdir}"
}

#****Start run****

if [[ $# -ne 1 ]]
then
    echo "Syntax: DM \"Excel file\""
    exit 0
fi

if [[ -e $1 ]]
then
    createXLzip $1
else
    echo "You misspelt the filename or it doesn't exist."
    exit 0
fi



#After the evaluation has been completed, we delete the zip file and zip folder
#created to hold extracted zip files.

#rm "${XLdir}.zip"
#rm -rf "${XLdir}"


